In [1]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
# function forward for prediction

def forward(x):
    yhat = w*x + b
    return yhat

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print('the prediction:', yhat)

the prediction: tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0], [2.0]])
print('The sahpe of x:', x.shape)

yhat = forward(x)
print('The prediction:', yhat)

The sahpe of x: torch.Size([2, 1])
The prediction: tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [6]:
# class Linear

from torch.nn import Linear
torch.manual_seed(1)

In [7]:
# create a Linear regression model, and print out the parameters

lr = Linear(in_features=1, out_features=1, bias=True)
print('Parameters w and b:', list(lr.parameters()))

Parameters w and b: [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
print('Python dictionary:', lr.state_dict())
print('keys:', lr.state_dict().keys())
print('values:', lr.state_dict().values())

Python dictionary: OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys: odict_keys(['weight', 'bias'])
values: odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [9]:
print('weight:', lr.weight)
print('bias:', lr.bias)

weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [10]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print('The prediction:', yhat)

The prediction: tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [11]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print('The prediction:', yhat)

The prediction: tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


In [14]:
# build custom modules

from torch import nn

In [15]:
# customize linear regression class

class LR(nn.Module):
    
    # constructor
    def __init__(self, input_size, output_size):
        
        # inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    # prediction function   
    def forward(self, x):
        out = self.linear(x)
        return out

In [16]:
lr = LR(1,1)
print('The parameters:', list(lr.parameters()))
print('The linear model:', lr.linear)

The parameters: [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
The linear model: Linear(in_features=1, out_features=1, bias=True)


In [17]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print('The prediction:', yhat)

The prediction: tensor([[0.2755]], grad_fn=<AddmmBackward>)


In [18]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print('The prediction:', yhat)

The prediction: tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)


In [19]:
print('python dictionary:', lr.state_dict())
print('keys:', lr.state_dict().keys())
print('values:', lr.state_dict().values())

python dictionary: OrderedDict([('linear.weight', tensor([[-0.1939]])), ('linear.bias', tensor([0.4694]))])
keys: odict_keys(['linear.weight', 'linear.bias'])
values: odict_values([tensor([[-0.1939]]), tensor([0.4694])])
